// Open Graph fields shared by the root layout and every demo route. A route that sets
// its own openGraph replaces the layout's object rather than merging into it, so
// demoMetadata() spreads these back in.
export const siteOpenGraph = {
  siteName: "Don Branson's Graph Visualization Showcase",
  locale: 'en_US',
  type: 'website',
} as const

// Cache-busting version for the share image URL. Next.js versions the home page's
// /opengraph-image URL itself, but demo routes list the image explicitly (below) and get the
// bare URL, which LinkedIn/X cache indefinitely. Vercel sets the commit SHA at build time;
// local builds fall back to the bare URL.
const imageVersion = process.env.VERCEL_GIT_COMMIT_SHA?.slice(0, 12)

// The social preview generated by src/app/opengraph-image.tsx. Next.js only adds it
// automatically to routes that don't set their own openGraph, so demoMetadata() lists it.
export const siteImage = {
  url: imageVersion ? `/opengraph-image?v=${imageVersion}` : '/opengraph-image',
  type: 'image/png',
  width: 1200,
  height: 630,
  alt: 'Graph Visualizations: knowledge graph and network demos by Don Branson',
}
