// Open Graph fields shared by the root layout and every demo route. A route that sets
// its own openGraph replaces the layout's object rather than merging into it, so
// demoMetadata() spreads these back in.
export const siteOpenGraph = {
  siteName: "Don Branson's Graph Visualization Showcase",
  locale: 'en_US',
  type: 'website',
} as const

// The social preview generated by src/app/opengraph-image.tsx. Next.js only adds it
// automatically to routes that don't set their own openGraph, so demoMetadata() lists it.
export const siteImage = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: 'Graph Visualizations: knowledge graph and network demos by Don Branson',
}
